// Product rating data from API
export interface ProductRating {
  rate: number;
  count: number;
}

// Product shape as returned by FakeStore API
export interface Product {
  id: number;
  title: string;
  price: number;
  description: string;
  category: string;
  image: string;
  rating: ProductRating;
}

// Shape sent when creating/updating a product (id and rating auto-generated by API)
export type ProductPayload = Omit<Product, 'id' | 'rating'>;
